language: node_js

dist: trusty

install:
  - npm install
  - npm install -g grunt-cli

script:
  - grunt browserify
  - npm test
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  chrome: stable
